# Site settings
title: The North Code
email: rob@robbollons.com
description: "Pursuing Programming Succinctness"
baseurl: ""
url: "http://thenorthcode.net"
twitter_username: robbollons
github_username: robbollons

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
gems:
  - jekyll-gist
