# Site settings
title: The North Code
email: rob@robbollons.com
description: "Developer | Designer | Joie de Vivre"
baseurl: ""
url: "http://thenorthcode.net"
twitter_username: robbollons
github_username: robbollons

# Build settings
markdown: kramdown
permalink: pretty
