# Site settings
title: Rob Bollons
email: rob@thedogsbollons.com
description: "Developer | Designer | Joie de Vivre"
baseurl: ""
url: "http://thedogsbollons.com"
twitter_username: robbollons
github_username: robbollons

# Build settings
markdown: kramdown
permalink: pretty
