# Site settings
title: The North Code
email: rob@robbollons.com
description: "Pursuing Programming Succinctness"
baseurl: ""
url: "http://thenorthcode.net"
twitter_username: robbollons
github_username: robbollons

defaults:
  -
    scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
      theme: "black"
      showcontrols: false
      showprogress: false
      usebrowserhistory: true
      center: false
      transition: "fade"


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
exclude:
  - bower.json
