# Site settings
title: The North Code
email: rob@thenorthcode.net
description: "Blog of Rob Bollons - Full Stack Developer | Joie de Vivre"
baseurl: ""
url: "http://thenorthcode.net"
twitter_username: robbollons
github_username: robbollons

# Build settings
markdown: kramdown
permalink: pretty
