title: mrbalihai
email: mrbalihai@protonmail.com
url: https://mrbalihai.github.io
goat_counter: "mrbalihai"
description: About
github_username: mrbalihai
remote_theme: riggraz/no-style-please
theme_config:
  date_format: "%Y-%m-%d"
